name: Manual NPM Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: >
          Type of semantic version bump to apply.
          - patch: bug fixes x.x.1
          - minor: new features x.1.X
          - major: breaking changes 1.x.x
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

      allow_release_notes:
        description: 'Check to allow this version bump to trigger a release note'
        required: true
        default: true
        type: boolean

      tag:
        description: 'Optional: specify a custom NPM tag for this release'
        required: false
        type: string


jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Bump package version
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
          BRANCH: ${{ github.ref_name }}
        run: bash .github/scripts/bump-version.sh

      - name: Build package
        run: npm run build

      - name: Publish to npm
        if: ${{ github.ref_name == 'development' || github.event.inputs.tag != '' }}
        uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: ${{ github.ref_name == 'development' && 'latest' || github.event.inputs.tag }}

      - name: Create GitHub Release with Generated Notes
        if: ${{ steps.publish.outcome == 'success' && github.event.inputs.allow_release_notes == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

